package com.privatelibrarian.app.data.local

import android.content.Context
import io.objectbox.BoxStore
import com.privatelibrarian.app.domain.model.MyObjectBox // This will be generated by ObjectBox

object ObjectBoxManager {
    lateinit var boxStore: BoxStore
        private set

    fun init(context: Context) {
        // MyObjectBox is generated by the ObjectBox plugin during build
        // boxStore = MyObjectBox.builder()
        //     .androidContext(context.applicationContext)
        //     .build()
    }
}
